config/routes.rb
Rails.application.routes.draw do
  root "patients#index"

  # resources :suppliers

  resources :patients do 
    resources :appointments
  end

  resources :physicians do 
    resources :appointments
  end 

end

app/models/account.rb
class Account < ApplicationRecord
  
  belongs_to :supplier
  has_one :account_history
end

app/models/account_history.rb
class AccountHistory < ApplicationRecord
  
  belongs_to :account
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :physician
  belongs_to :patient
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/patient.rb
class Patient < ApplicationRecord
    has_many :appointments , dependent: :destroy
    has_many :physicians , through: :appointments
    accepts_nested_attributes_for :appointments
end

app/models/physician.rb
class Physician < ApplicationRecord
    has_many :appointments , dependent: :destroy
    has_many :patients , through: :appointments
end

app/models/programmer.rb
class Programmer < ApplicationRecord
end

app/models/programmer_client.rb
class ProgrammerClient < ApplicationRecord
  belongs_to :client
  belongs_to :programmer
end

app/models/supplier.rb
class Supplier < ApplicationRecord
    has_one :account, dependent: :destroy
    has_one :account_history , through: :account
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
    @patients = Patient.all
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def new
    @patient = Patient.new
    @patient.appointments.build
  end

  def create 
    @patient = Patient.create(patient_params)
    if @patient.save 
      redirect_to @patient
    end
  end

  def edit
    @patient = Patient.find(params[:id])
  end

  def update
    @patient = Patient.find(params[:id])
    if @patient.update(patient_params)
      redirect_to @patient
    end 
  end

  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy

    redirect_to @patient
  end

  private

  def patient_params
 params.require(:patient).permit(:name,appointments_attributes:[:appointment_date , :physician_id])
  end
end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  def index
    @physicians = Physician.all
  end

  def show
    @physician = Physician.find(params[:id])
  end

  def new
    @physician = Physician.new
  end

  def create
    @physician = Physician.create(physician_params)
    if @physician.save
      redirect_to @physician
    end 
  end

  def edit
    @physician = Physician.find(params[:id])
  end

  def update
  @physician = Physician.find(params[:id])
    if @physician.update(physician_params) 
     redirect_to @physician
    end
  end

  def destroy
    @physician = Physician.find(params[:id])
    @physician.destroy 

    redirect_to @physician
  end 
  
  def physician_params
  params.require(:physician).permit(:name)  
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  def index
    @suppliers = Supplier.all
  end

  def show
    @supplier = Supplier.find(params[:id])
  end

  def new
    @supplier = Supplier.new
  end

  def edit
    @supplier = Supplier.find(supplier_params)
    if @supplier.save
      redirect_to @supplier

    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def text_field_with_label(form , att)
    form.label(att) + form.text_field(att)
  end
  def coll_select(f , att)
      f.check_box(att) + f.label(att)
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActiveRecAssociation</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'partials/nav' %>
    <%=  yield %>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/partials/_form.html.erb
<div class="container">
  <div class="row justify-content-center align-items-center" style="height:100vh;">
    <div class="col-md-6">
      <%= form_with(model: @patient ) do |f| %>
        <form class="row g-3">
          <div class="col-md-12">
            <%= f.label :name, class: "form-label" %>
            <%= f.text_field :name, placeholder: "Enter Your Name", class: "form-control" %>
          </div>
          
          <%= f.fields_for :appointments do |a| %>
            <div class="col-md-6">
              <%= a.label :appointment_date ,class: "form-label" %>
              <%= a.date_field :appointment_date , placeholder: "Enter Your Name", class:"form-control" %>
            </div>
            <div class="col-md-6">
              <%= a.label :physician_id ,class: "form-label" %>
              <%= a.collection_select :physician_id , Physician.all , :id , :name , placeholder: "Enter Your Name", class:"form-control" %>
            </div>
          <% end %>

          <div class="col-md-12">
            <%= f.submit "Create patient", class: "btn btn-primary" %>
          </div>
        </form>
      <% end %>
    </div>
  </div>
</div>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark ">
  <a class="navbar-brand" href="#">ASSOCIATION</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active pr-3 ">
             <%= link_to 'PATIENT_PORTAL' , root_path %> <span class="sr-only">(current)</span>
      </li>
      <li class="nav-item active">
             <%= link_to 'DOCTOR_PORTAL' , physicians_path %> <span class="sr-only">(current)</span>
      </li>
    </ul>
  </div>
</nav>