config/routes.rb
Rails.application.routes.draw do
  root "patients#index"

  # resources :suppliers

  resources :patients do 
    resources :appointments
  end

  resources :physicians do 
    resources :appointments
  end 

end

app/models/account.rb
class Account < ApplicationRecord
  
  belongs_to :supplier
  has_one :account_history
end

app/models/account_history.rb
class AccountHistory < ApplicationRecord
  
  belongs_to :account
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :physician
  belongs_to :patient
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/patient.rb
class Patient < ApplicationRecord
    has_many :appointments , dependent: :destroy
    has_many :physicians , through: :appointments
    accepts_nested_attributes_for :appointments
end

app/models/physician.rb
class Physician < ApplicationRecord
    has_many :appointments , dependent: :destroy
    has_many :patients , through: :appointments
end

app/models/programmer.rb
class Programmer < ApplicationRecord
end

app/models/programmer_client.rb
class ProgrammerClient < ApplicationRecord
  belongs_to :client
  belongs_to :programmer
end

app/models/supplier.rb
class Supplier < ApplicationRecord
    has_one :account, dependent: :destroy
    has_one :account_history , through: :account
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
    @patients = Patient.all
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def new
    @patient = Patient.new
    @patient.appointments.build
  end

  def create 
    @patient = Patient.create(patient_params)
    if @patient.save 
      redirect_to @patient
    end
  end

  def edit
    @patient = Patient.find(params[:id])
  end

  def update
    @patient = Patient.find(params[:id])
    if @patient.update(patient_params)
      redirect_to @patient
    end 
  end

  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy

    redirect_to @patient
  end

  private

  def patient_params
 params.require(:patient).permit(:name,appointments_attributes:[:appointment_date , :physician_id])
  end
end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  def index
    @physicians = Physician.all
  end

  def show
    @physician = Physician.find(params[:id])
  end

  def new
    @physician = Physician.new
  end

  def create
    @physician = Physician.create(physician_params)
    if @physician.save
      redirect_to @physician
    end 
  end

  def edit
    @physician = Physician.find(params[:id])
  end

  def update
  @physician = Physician.find(params[:id])
    if @physician.update(physician_params) 
     redirect_to @physician
    end
  end

  def destroy
    @physician = Physician.find(params[:id])
    @physician.destroy 

    redirect_to @physician
  end 
  
  def physician_params
  params.require(:physician).permit(:name)  
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  def index
    @suppliers = Supplier.all
  end

  def show
    @supplier = Supplier.find(params[:id])
  end

  def new
    @supplier = Supplier.new
  end

  def edit
    @supplier = Supplier.find(supplier_params)
    if @supplier.save
      redirect_to @supplier

    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def text_field_with_label(form , att)
    form.label(att) + form.text_field(att)
  end
  def coll_select(f , att)
      f.check_box(att) + f.label(att)
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/patients/edit.html.erb
<h1>Edit The Patient Details</h1>
<%= render 'partials/form' %>

app/views/patients/index.html.erb
<%= link_to 'New Create ', new_patient_path %>
<legend> patients </legend>
<table class="table mt-5 table-striped ">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Name</th>
      <th scope="col">Doctor</th>
      <th scope="col">appointment_date</th>
    </tr>
  </thead>
  <tbody>
    <% @patients.each do |p| %> 
        <tr>
            <td><%= p.id %></td>
            <td><%= p.name %></td>
            <% p.appointments.each do |date| %>
                <td><%= date.physician.name  %></td>     
                <td><%= date.appointment_date  %></td>     
            <% end %>
                <td><%= link_to 'View', patient_path(p) %></td>     
        </tr>
    <% end %>
  </tbody>
</table>

app/views/patients/new.html.erb
<h1>Fill Patient Details</h1>
<%= render 'partials/form' %>

app/views/patients/show.html.erb
<table class="table">
  <thead >
    <tr>
      <th scope="col">DETAILS OF THE PATIENT</th>
      <th colspan="2" scope="col" >
        <%= link_to 'EDIT', edit_patient_path %>
        <%= link_to 'DELETE', patient_path(@patient) ,data:
        {
          turbo_method: :delete ,
          turbo_confirm: "Are Sure Want to delete Patient ? "
        }, class: "style:red" %>
      </th>
    </tr>
  </thead>
  <tbody>
    <tr>
        <td>Id : </td>
        <td><%= @patient.id %></td>
    </tr>
    <tr>
        <td>Name : </td>
        <td><%= @patient.name %></td>
    </tr>
    <tr>
        <td>Appointment Date </td>
        <td>
          <% @patient.appointments.each do |date| %>
            <%= date.appointment_date %> 
          <% end %>
        </td>
    </tr>
  </tbody>
</table>

app/views/physicians/edit.html.erb
<h1>Edit The physician Details</h1>
<h1>Fill Physician Details</h1>
<%= form_with(model: @physician ) do |f| %>
<div>

 <%= f.label :name %>
 <%= f.text_field :name , palceholder: "Enter Your Name" %>
</div>
<div>
    <%= f.submit "Create DOCTOR" %>
</div>

<% end %>

app/views/physicians/index.html.erb
<%= link_to 'New Create ', new_physician_path %>
<fieldset>
<legend> DOCTOR </legend>
<table class="table mt-5 table-striped ">

  <thead class="thead-dark">
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Name</th>

      <th scope="col">Patient</th>
      <th scope="col">appointment_date</th>
      
    </tr>
  </thead>
  <tbody>
    <% @physicians.each do |ph| %> 
        <tr>
            <td><%= ph.id %></td>
            <td><%= ph.name %></td>
            <% ph.appointments.each do |date| %>

                <td><%= date.patient.name %></td> 
                <td><%= date.appointment_date %></td> 
                
            <% end %>

            <td><%= link_to 'View', physician_path(ph) %></td>
        </tr>
    <% end %>
  </tbody>
</table>
</fieldset>

app/views/physicians/new.html.erb
<h1>Fill Physician Details</h1>
<%= form_with(model: @physician ) do |f| %>
<div>

 <%= f.label :name %>
 <%= f.text_field :name , palceholder: "Enter Your Name" %>
</div>
<div>
    <%= f.submit "Create DOCTOR" %>
</div>

<% end %>

app/views/physicians/show.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">DETAILS OF THE Physician</th>
      <th colspan="2" scope="col" >
        <%= link_to 'EDIT', edit_physician_path %>
        <%= link_to 'DELETE', physician_path(@physician) ,data:
        {
          turbo_method: :delete ,
          turbo_confirm: "Are Sure Want to delete Physician ? "
        }, class: "style:red" %>
      </th>
    </tr>
  </thead>
  <tbody>
    <tr>
        <td>Id : </td>
        <td><%= @physician.id %></td>
    </tr>
    <tr>
        <td>Name : </td>
        <td><%= @physician.name %></td>
    </tr>
  <% i=0 %> 
  <% @physician.appointments.each do |p| %>

      <% i+=1 %> 
    <tr>
      <td>patient Name <%= i %> </td>
      <td>
          <strong> <%= p.patient.name %> </strong>
      </td>
    </tr>
    <tr>
      <td>Appointment Date:   </td>
      <td>
           <%= p.appointment_date %>
      </td>
    </tr>
  <% end %>

  </tbody>
</table>

app/views/suppliers/edit.html.erb
<h1>Suppliers#edit</h1>
<p>Find me in app/views/suppliers/edit.html.erb</p>

app/views/suppliers/index.html.erb
<h1>Hash_one - Belongs To</h1>
<table class="table mt-5 table-striped ">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Name</th>
      <th scope="col">account_Number</th>

    </tr>
  </thead>
  <tbody>
    <% @suppliers.each do |s| %> 
        <tr>
            <td><%= s.id %></td>
            <td><%= s.name %></td>
                <td><%= s.account.account_number if s.account.present? %></td> 
        </tr>
    <% end %>
  </tbody>
</table>

app/views/suppliers/new.html.erb
<%= form_with(model: @supplier) do |f| %>
<div>
    <%= f.label :name  %>
    <%= f.text_field :name , placeholder: "Enter Your name"  %>
</div>
<% end %>

app/views/suppliers/show.html.erb
<h1>Suppliers#show</h1>
<p>Find me in app/views/suppliers/show.html.erb</p>